<script setup>
	import VueCard from '~/components/VueCard.vue';
	import VueLink from '~/components/VueLink.vue';

	console.log('cic');
</script>

<template>
	<NuxtLayout>
		<h2 class="text-4xl max-sm:text-3xl font-bold tracking-tight text-white">
			<span class="block">
				<img
					class="inline-block h-[120px] w-[120px] max-sm:h-[100px] max-sm:w-[100px] rounded-full border border-4"
					src="~/assets/img/avatar.jpg"
					alt="My beautiful self generated by stable diffusion in the AI app called lensa"
				/>
			</span>

			<span class="block mt-4">
				Patrik Jánosdeák
			</span>

			<h3 class="text-2xl max-sm:text-xl font-bold tracking-tight text-white">
				<div class="flex items-center">
					<span class="px-2 max-sm:text-2xl">
						👉
					</span>

					<span>
						Full-stack Developer
					</span>

					<span class="px-2 max-sm:text-2xl">
						👈
					</span>
				</div>
			</h3>
		</h2>

		<div class="mt-4 flex items-center justify-center gap-x-4 gap-y-4">
			<VueButton
				href="https://twitter.com/stepsovich"
				icon="bi-twitter"
				icon-color="text-[#00acee]"
				title="My Twitter profile"
			>
				Twitter
			</VueButton>

			<VueButton
				href="https://www.linkedin.com/in/patrik-janosdeak/"
				icon="bi-linkedin"
				icon-color="text-[#0072b1]"
				title="My Linkedin profile"
			>
				Linkedin
			</VueButton>

			<VueButton
				href="https://github.com/truesteps"
				icon="bi-github"
				title="My Github profile"
			>
				Github
			</VueButton>
		</div>

		<VueCard class="mt-6">
			<p class="mx-auto max-w-xl text-left text-lg max-sm:text-sm leading-8 text-white">
				Currently hacking marketing asset generation at

				<VueLink class="text-gray-300 no-underline opacity-40" href="#" title="Imagelance website link">
					<VueIcon name="ri-loader-2-line" class="animate-spin-slow mr-[-4px]" />

					imagelance.com
				</VueLink>
			</p>
		</VueCard>

		<p class="mx-auto mt-4 max-w-xl text-left text-lg max-sm:text-md leading-8 text-white">
			An ex pro-gamer wannabe turned programmer. Fullstack dev working with
			<VueLink href="https://laravel.com/" title="Laravel website">Laravel</VueLink>,
			<VueLink href="https://vuejs.org/" title="Vue website">Vue</VueLink> and
			<VueLink href="https://nodejs.org/" title="Node website">Node</VueLink>. Fueled by shit tons of ☕.
		</p>
	</NuxtLayout>
</template>
